# This module is a bootstrap root (it creates the state bucket itself), so it
# carries its own replica provider. The default `aws` provider is generated by
# live/**/root.hcl like every other unit.
provider "aws" {
  alias  = "replica"
  region = coalesce(var.replica_region, var.region)
}
